### ISSUE TITLE
HSNELouvainDemo fails with OSError: [WinError 126] 

### ISSUE THREAD

**Issue by bldrvnlw** [biovault/nptsne#3]
> >python testhsnelouvain.py

> Traceback (most recent call last):
>   File "testhsnelouvain.py", line 5, in <module>
>     import community as community_louvain
>   File "C:\Users\bvanlew\Anaconda3\envs\p37hsnedemo\lib\site-packages\community\__init__.py", line 9, in <module>
>     from .community_louvain import (
>   File "C:\Users\bvanlew\Anaconda3\envs\p37hsnedemo\lib\site-packages\community\community_louvain.py", line 12, in <module>
>     import networkx as nx
>   File "C:\Users\bvanlew\Anaconda3\envs\p37hsnedemo\lib\site-packages\networkx\__init__.py", line 112, in <module>
>     import networkx.generators
>   File "C:\Users\bvanlew\Anaconda3\envs\p37hsnedemo\lib\site-packages\networkx\generators\__init__.py", line 8, in <module>
>     from networkx.generators.community import *
>   File "C:\Users\bvanlew\Anaconda3\envs\p37hsnedemo\lib\site-packages\networkx\generators\community.py", line 20, in <module>
>     from scipy.special import zeta as _zeta
>   File "C:\Users\bvanlew\Anaconda3\envs\p37hsnedemo\lib\site-packages\scipy\__init__.py", line 136, in <module>
>     from . import _distributor_init
>   File "C:\Users\bvanlew\Anaconda3\envs\p37hsnedemo\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
>     WinDLL(os.path.abspath(filename))
>   File "C:\Users\bvanlew\Anaconda3\envs\p37hsnedemo\lib\ctypes\__init__.py", line 364, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found

**Comment by bldrvnlw** [comment]
This occurred with scipy 1.5.2. Downgrading to scipy 1.4.1 fixes the problem.

TODO Update the requirements.txt with the working version of scipy

**Comment by bldrvnlw** [comment]
Appears to have been reported in scipy https://github.com/scipy/scipy/issues/12400. Even though it suggests that this has been fixed in 1.5.1 neither 1.5.1 or 1.5.2 of scipy fix the issue. Downgrading to 1.4.1 is still currently the workaround
